language: haskell
before_install:
  - cabal update

install:
  - cabal install --only-dependencies
  - cabal configure -flib-Werror $mode
  - cabal build

env:
  - mode=""
  # - mode="--enable-tests" script="cabal test --show-details=always"
